name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - current
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: "UTC"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Pagefind
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: cloudcannon/pagefind

      - name: Set commit variables
        run: |
          echo "HUGO_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "HUGO_COMMIT_TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
          echo "HUGO_COMMIT_DATE=$(git log -1 --date=format-local:'%Y-%m-%d %H:%M:%S UTC' --pretty=%cd)" >> $GITHUB_ENV

      - name: Build with Hugo
        run: |
            mkdir -p data
            echo "url: `git config --get remote.origin.url`" > data/repo.yaml
            hugo --minify

      - name: Build search index
        run: |
            pagefind
            hugo --minify

      - name: Deploy to Cloudflare Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/current' || github.event_name == 'workflow_dispatch'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=esphome-docs
